apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: message-worker
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app.kubernetes.io/name: message-worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s

