apiVersion: v1
kind: Secret
metadata:
  name: message-worker-secrets
  namespace: app
type: Opaque
stringData:
  MONGODB_URI: "mongodb://chat:TROQUE_ESTA_SENHA@mongodb-0.mongodb-headless.data.svc.cluster.local:27017,mongodb-1.mongodb-headless.data.svc.cluster.local:27017,mongodb-2.mongodb-headless.data.svc.cluster.local:27017/chat?replicaSet=rs0&authSource=chat"
  REDIS_URL: "redis://:TROQUE_ESTA_SENHA@redis-master.data.svc.cluster.local:6379/0"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/CONTA/chat-messages"
  SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:CONTA:chat-notifications"
  # Use estas tres linhas somente se os pods nao conseguirem usar o
  # LabInstanceProfile da EC2. As credenciais do Academy expiram.
  # AWS_ACCESS_KEY_ID: "ASIA..."
  # AWS_SECRET_ACCESS_KEY: "..."
  # AWS_SESSION_TOKEN: "..."
