grafana:
  adminPassword: TROQUE_ESTA_SENHA
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 3d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

alertmanager:
  enabled: false

